spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_database
    username: root
    password: Germany1#
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
